[Mime]
webbrowser/available=
email/available=
file_manager/available=
screensaver/available=
composite_manager/available=
desktop_manager/available=
power_manager/available=
polkit/available=
im/available=
widget/available=
terminal_manager/available=
audio_player/available=
video_player/available=
pdf_reader/available=
image_display/available=
text_editor/available=
archive/available=
spreadsheet/available=
bittorent/available=
document/available=
burn/available=
tasks/available=
webbrowser/installed=Chromium,/usr/bin/chromium,chromium,/usr/share/applications/chromium.desktop,;
email/installed=
file_manager/installed=ranger,ranger,utilities-terminal,/usr/share/applications/ranger.desktop,;
screensaver/installed=
composite_manager/installed=
desktop_manager/installed=Customize Look and Feel,lxappearance,preferences-desktop-theme,/usr/share/applications/lxappearance.desktop,;Desktop Session Settings,lxsession-edit,preferences-desktop,/usr/share/applications/lxsession-edit.desktop,;Default applications for LXSession,lxsession-default-apps,preferences-desktop,/usr/share/applications/lxsession-default-apps.desktop,;
power_manager/installed=
polkit/installed=
im/installed=Telegram,Telegram,org.telegram.desktop,/usr/share/applications/org.telegram.desktop.desktop,;
widget/installed=
terminal_manager/installed=UXTerm,uxterm,xterm-color_48x48,/usr/share/applications/uxterm.desktop,;kitty,kitty,kitty,/usr/share/applications/kitty.desktop,;kitty URL Launcher,kitty,kitty,/usr/share/applications/kitty-open.desktop,;urxvt (client),urxvtc,terminal,/usr/share/applications/urxvtc.desktop,;urxvt,urxvt,terminal,/usr/share/applications/urxvt.desktop,;urxvt (tabbed),urxvt-tabbed,terminal,/usr/share/applications/urxvt-tabbed.desktop,;XTerm,xterm,xterm-color_48x48,/usr/share/applications/xterm.desktop,;
audio_player/installed=Volume Control,pavucontrol,org.pulseaudio.pavucontrol,/usr/share/applications/org.pulseaudio.pavucontrol.desktop,;Qt V4L2 video capture utility,qvidcap,qvidcap,/usr/share/applications/qvidcap.desktop,;Qt V4L2 test Utility,qv4l2,qv4l2,/usr/share/applications/qv4l2.desktop,;mpv Media Player,mpv,mpv,/usr/share/applications/mpv.desktop,;
video_player/installed=Volume Control,pavucontrol,org.pulseaudio.pavucontrol,/usr/share/applications/org.pulseaudio.pavucontrol.desktop,;Qt V4L2 video capture utility,qvidcap,qvidcap,/usr/share/applications/qvidcap.desktop,;Qt V4L2 test Utility,qv4l2,qv4l2,/usr/share/applications/qv4l2.desktop,;mpv Media Player,mpv,mpv,/usr/share/applications/mpv.desktop,;
pdf_reader/installed=feh,feh,feh,/usr/share/applications/feh.desktop,;Zathura,zathura,org.pwmt.zathura,/usr/share/applications/org.pwmt.zathura-pdf-mupdf.desktop,;Zathura,zathura,org.pwmt.zathura,/usr/share/applications/org.pwmt.zathura.desktop,;
image_display/installed=feh,feh,feh,/usr/share/applications/feh.desktop,;Zathura,zathura,org.pwmt.zathura,/usr/share/applications/org.pwmt.zathura-pdf-mupdf.desktop,;Zathura,zathura,org.pwmt.zathura,/usr/share/applications/org.pwmt.zathura.desktop,;
text_editor/installed=Code - OSS - URL Handler,code-oss,com.visualstudio.code.oss,/usr/share/applications/code-url-handler.desktop,;Code - OSS,code-oss,com.visualstudio.code.oss,/usr/share/applications/code-oss.desktop,;Code - OSS - URL Handler,code-oss,com.visualstudio.code.oss,/usr/share/applications/code-oss-url-handler.desktop,;Neovim,nvim,nvim,/usr/share/applications/nvim.desktop,;
archive/installed=
spreadsheet/installed=LibreOffice Calc,libreoffice,libreoffice-calc,/usr/share/applications/libreoffice-calc.desktop,;
bittorent/installed=
document/installed=LibreOffice Writer,libreoffice,libreoffice-writer,/usr/share/applications/libreoffice-writer.desktop,;
burn/installed=
tasks/installed=Stacer,stacer,stacer,/usr/share/applications/stacer.desktop,;
