[module/space]
type = custom/text
format = " "
;----------------------------------------------------------

[module/left]
type = custom/text
format = ❱
format-font = 1
format-padding = 1
format-foreground = ${color.brightwhite}

;----------------------------------------------------------
[module/right]
type = custom/text
format = ❰
format-font = 1
format-padding = 1
format-foreground = ${color.brightwhite}

;----------------------------------------------------------
[module/todo]
type = custom/text
format = ""
; format = " "
click-left = dmenu_todo
format-font = 1
format-padding = 1
format-background = ${color.yellow}
format-foreground = ${color.background}

;----------------------------------------------------------
[module/monitor]
type = custom/text
format = "󰍺 "
click-left = dmenu_monitor
click-right = arandr
format-font = 3
format-padding = 1
format-background = ${color.yellow}
format-foreground= ${color.background}

;----------------------------------------------------------
[module/dswitcher]
type = custom/text
format = ""
click-left = rofi -show window
format-font = 1
format-padding = 1
format-background = ${color.yellow}
format-foreground= ${color.background}

;----------------------------------------------------------
[module/drun]
type = custom/text
format = ""
click-left = rofi -show run
format-font = 1
format-padding = 1
format-background = ${color.yellow}
format-foreground= ${color.background}

;----------------------------------------------------------
[module/dmenu]
type = custom/text
format = 
click-left = rofi -show drun
format-font = 1
format-padding = 1
format-background = ${color.yellow}
format-foreground= ${color.background}

;----------------------------------------------------------
[module/eject]
type = custom/text
format = 
click-left =   dmenu_udiskie -dmenu  -fn "Iosevka-11" -nb "#282828" -nf "#ebdbb2" -sb "#d79921" -w "800" -x "300" -y "220" -p "Storage" -i -l 10
format-font = 1
format-padding = 1
format-background = ${color.yellow}
format-foreground= ${color.background}

;----------------------------------------------------------
[module/screenshot]
type = custom/text
format = "󰹑 "
click-left = flameshot gui
click-right = flameshot full -p ~/Pictures/screenshot
format-font = 3
format-padding = 1
format-background = ${color.yellow}
format-foreground= ${color.background}

;----------------------------------------------------------
[module/youtube]
type = custom/text
format = ""
click-left = dmenu_mager
format-font = 1
format-padding = 1
format-background = ${color.yellow}
format-foreground= ${color.background}

;----------------------------------------------------------
[module/polybar-restart]
type = custom/text
format = 
click-left = polybar-msg cmd restart
format-font = 1
format-padding = 1
format-background = ${color.yellow}
format-foreground= ${color.background}

;----------------------------------------------------------
[module/systray]
; inherit = etc/base
type = custom/text
format = 
click-left = ~/.config/polybar/scripts/systray
format-font = 1
format-padding = 1

;----------------------------------------------------------
[module/window]
type = internal/xwindow
format = <label>
format-prefix = "穀 "
format-font = 1

label = %title%
label-font = 3
label-padding = 1
label-maxlen = 55

label-empty =  Desktop    Place    Mager    Hell Text Editor    Hell Browser
label-empty-font = 3
; label-empty = Desktop
label-empty-padding = 1

[module/min]
type = custom/text
format-foreground =${color.green}
click-left = i3-msg move scratchpad
format = ﱣ
format-padding = 1

;----------------------------------------------------------
[module/max]
type = custom/text
format-foreground =${color.yellow}
click-left = i3-msg scratchpad show floating toggle
format = ﱣ
format-padding = 1

;----------------------------------------------------------
[module/close]
type = custom/text
format-foreground =${color.red}
click-left = i3-msg kill
format = ﱣ
format-padding = 1

;----------------------------------------------------------

[module/droidcam]
type = custom/text
click-left = droidcam-cli 192.168.43.1 4747
click-right = pkill -9 droidcam-cli
format = 
format-padding =1
